version: "3.7"

services:
  db:
    container_name: koc-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - koc-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: koc
      MYSQL_DATABASE: koc

  mq:
    container_name: koc-mq
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"


volumes:
  koc-data:
