social-login:
  kakao:
    client_id: "350e38b3eb9c43bd8f47ce44d19ef349"
    redirect_uri: "http://localhost:8080/auth"
    oauth_uri: "https://kauth.kakao.com/oauth"
    kapi_user_info_uri: "https://kapi.kakao.com/v2/user/me"
    javascript_key: "819d78cdd08a6a1d4652bc9f5806bf20"

jwt:
  password: "testPassword"

---

spring:
  config.activate.on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS KOC
    username: sa
    password: 1234
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

---

spring:
  config.activate.on-profile: test
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/koc
    username: root
    password: 123
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---

spring:
  config.activate.on-profile: prd
  datasource:
    url: jdbc:mysql://121.167.132.221:3306/place
    username: koc-place
    password: 2012
  jpa:
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: 121.167.132.221
    port: 5672
    username: guest
    password: guest