spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/koc
    username: root
    password: koc
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
spring:
  config.activate.on-profile: local

---
spring:
  config.activate.on-profile: test

---
spring:
  config.activate.on-profile: prd
  datasource:
    url: jdbc:mysql://koc-db/koc
    username: root
    password: koc
  rabbitmq:
    host: koc-mq
    port: 5672
    username: guest
    password: guest
