spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/koc
    username: root
    password: koc
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
spring:
  config.activate.on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

---
spring:
  config.activate.on-profile: test
  jpa:
    show-sql: true

---
spring:
  config.activate.on-profile: prd
  datasource:
    url: jdbc:mysql://121.167.132.221:3306/place
    username: koc-place
    password: 2012
  jpa:
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: 121.167.132.221
    port: 5672
    username: guest
    password: guest
